# Generated by Django 4.1.5 on 2023-06-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('joylashuv', models.CharField(max_length=500)),
                ('vidio', models.FileField(upload_to='manzil-vidios/')),
            ],
        ),
    ]
