# Generated by Django 4.1.5 on 2023-06-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rasmi',
            field=models.ImageField(default=1, upload_to='film-rasmlar'),
            preserve_default=False,
        ),
    ]
