# Generated by Django 4.1.5 on 2023-06-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilovalar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilova',
            name='rasm',
            field=models.ImageField(default=1, upload_to='ilova-rasmlar'),
            preserve_default=False,
        ),
    ]
