# Generated by Django 4.1.5 on 2023-06-06 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='ilova-rasmlar')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('pdf', models.FileField(upload_to='pdf/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitoblar.category')),
            ],
        ),
    ]
